### ISSUE TITLE
Make this usable as a standard repo?

### ISSUE THREAD

**Issue by kigerpunk** [robotanarchy/void-packages-bleeding-edge#1]
I'm not yet familiar with how xbps organises things, but would it pe possible to configure things such that this repo could be added to `/etc/xbps.d/`?

**Comment by robotanarchy** [comment]
As far as I can tell, it doesn't work that way. You'd usually have to get your package into the official [void-packages](https://github.com/voidlinux/void-packages) repository - but sway wasn't accepted, as it is not released yet, so I made this overlay repository.

Getting overlays supported upstream is discussed [here](https://github.com/voidlinux/void-packages/issues/3218). Thanks for asking, I'll add this link to the README.md file.
