### ISSUE TITLE
Sway and wlc have versions!

### ISSUE THREAD

**Issue by kigerpunk** [robotanarchy/void-packages-bleeding-edge#3]
https://github.com/Cloudef/wlc/releases/tag/v0.0.1

https://github.com/SirCmpwn/sway/releases/tag/0.3

They're pre-release, but hopefully still suitable for Void packaging.

**Comment by robotanarchy** [comment]
nice! I'm not currently doing much with my void installation, but please go ahead, adjust my packages and submit a PR to the official void-linux repo. Then void would be among the first repos to provide binary packages for sway and wlc :)

**Comment by kigerpunk** [comment]
I still haven't figured out how to write templates, but I have to start somewhere. I'll give it a try at some point.
